name: Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  server-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Brings code of branch that need to merge in main
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: |
          npm start &
          sleep 5
      
      - name: Test API endpoint
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/api/health)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "✅ API is working"
          else
            echo "❌ API check failed"
            exit 1
          fi


  frontend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Brings code of branch that need to merge in main
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Make Frontend Build
        run: npm run build




